name: "Comment on JIRA issue"

description: "Comment on JIRA issue on JIRA Server"

inputs:
  jira_base_url:
    description: JIRA Server base url
    required: true
  jira_username:
    description: JIRA Server username
    required: true
  jira_password:
    description: JIRA Server password
    required: true
  issue_key:
    description: Issue key to comment on
    required: true
  issue_comment_text:
    description: The actual comment
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
